sheets:
  - name: "収入"
    description: "事業収入やその他の収入を記録するシート"
    columns:
      - name: "取引ID"
        description: "自動採番や日付＋連番で一意のIDを付与"
        type: "string"
      - name: "取引日"
        description: "収入が発生した日付"
        type: "date"
      - name: "収入種別"
        description: "事業収入、給与、副収入など"
        type: "string"
      - name: "金額"
        description: "収入の金額"
        type: "number"
      - name: "取引先"
        description: "クライアントや取引先の名称"
        type: "string"
      - name: "備考"
        description: "メモや詳細情報"
        type: "string"

  - name: "経費"
    description: "経費の記録と管理を行うシート"
    columns:
      - name: "取引ID"
        description: "自動採番または入力による一意のID"
        type: "string"
      - name: "取引日"
        description: "経費が発生した日付"
        type: "date"
      - name: "経費種別"
        description: "交通費、通信費、交際費、消耗品費など"
        type: "string"
      - name: "金額"
        description: "経費の金額"
        type: "number"
      - name: "支払い方法"
        description: "現金、クレジットカード、銀行振込など"
        type: "string"
      - name: "領収書URL/画像リンク"
        description: "領収書や関連資料へのリンク"
        type: "string"
      - name: "備考"
        description: "その他メモ"
        type: "string"

  - name: "控除"
    description: "各種控除や特例の情報を管理するシート"
    columns:
      - name: "控除ID"
        description: "自動採番や入力による一意のID"
        type: "string"
      - name: "控除種別"
        description: "医療費控除、寄附金控除、社会保険料控除など"
        type: "string"
      - name: "対象年度"
        description: "控除が適用される年度"
        type: "string"
      - name: "金額"
        description: "控除に該当する金額"
        type: "number"
      - name: "備考"
        description: "詳細情報やメモ"
        type: "string"

  - name: "集計"
    description: "収入、経費、控除のデータを基に自動計算やレポートを作成するシート"
    columns:
      - name: "期間開始"
        description: "集計期間の開始日"
        type: "date"
      - name: "期間終了"
        description: "集計期間の終了日"
        type: "date"
      - name: "総収入額"
        description: "収入シートの金額の合計"
        type: "number"
      - name: "総経費額"
        description: "経費シートの金額の合計"
        type: "number"
      - name: "所得"
        description: "総収入額から総経費額を引いた金額"
        type: "number"
      - name: "控除合計"
        description: "対象期間の控除合計"
        type: "number"
      - name: "課税所得"
        description: "所得から控除を差し引いた金額"
        type: "number"
      - name: "推定税額"
        description: "最新の税率に基づいた計算結果"
        type: "number"

  - name: "設定"
    description: "税率や計算パラメータ、その他固定値を管理するシート"
    columns:
      - name: "パラメータ名"
        description: "設定項目の名前（例: 所得税率、住民税率、控除上限など）"
        type: "string"
      - name: "値"
        description: "設定値"
        type: "string"
      - name: "説明"
        description: "設定内容の詳細説明"
        type: "string"
